# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-17 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(unique=True, upload_to='photo/%Y/%m/%d/', verbose_name='轮播图')),
                ('info', models.TextField(blank=True, max_length=1000, verbose_name='信息')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '照片墙',
                'verbose_name_plural': '照片管理',
                'ordering': ('-created_time',),
            },
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ('-created_time',), 'verbose_name': '文章', 'verbose_name_plural': '文章管理'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '类目', 'verbose_name_plural': '类目管理'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签管理'},
        ),
    ]
